#define CLAN_NEW_INBRACKETS	0
#define CLAN_NEW_BRACKETCOLOUR	1
#define CLAN_NEW_REDO		2
#define CLAN_MENU		3
#define CLAN_ADMIN_MENU		4
#define CLAN_ADMIN_NAME1	5
#define CLAN_ADMIN_NAME2	6
#define CLAN_ADMIN_NAME3	7
#define CLAN_ADMIN_NAME4	8

